name: Mypy

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy types-PyYAML types-python-dateutil
      - name: Analysing the code with mypy
        run: |
          mypy --explicit-package-bases --ignore-missing-imports --exclude venv .
